os:
  - osx
language: node_js
node_js:
  - "8.5"
jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: build
      script: npm run build
    - stage: prepublish
      script: npm run prepublish
