language: node_js
branches:
  only:
    - master
node_js:
  - "8.11"
cache:
  directories:
    - node_modules # NPM packages
before_install:
  - sudo apt-get update -q
install:
  - npm install
jobs:
  include:
    - script: npm run lint
    - script: npm run sass-lint
