language: node_js
node_js:
  - "8.9"
jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: build
      script: npm run build
    - stage: prepublish
      script: npm run prepublish
