name: CI
on:
  push:
    branches: [ master ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Set node version
      - uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'

      # Cache node_modules
      - uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install node modules
        run: npm ci

      - name: Preflight
        run: npm run preflight
  publish:
    needs: [CI]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'
      - run: npm ci
      - run: npm run build
      - uses: complexdatacollective/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}

