name: Publish package to GitHub Packages
on:
  # the 1st condition
  workflow_run:
    workflows: ["preflight"]
    types:
      - completed

jobs:
  publish:
    needs: preflight
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '18.12.1'
      - run: npm ci
      - uses: complexdatacollective/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
